export const ADD_CHILD = 'ADD_CHILD'
export const SELECT_LAYER = 'SELECT_LAYER'
export const TOGGLE_DIRECTION = 'TOGGLE_DIRECTION'
export const SELECT_ELEMENT = 'SELECT_ELEMENT'

export const DOWNLOAD_PROYECT = 'DOWNLOAD_PROYECT'

export const DOWNLOAD_REQUEST = 'DOWNLOAD_REQUEST'
export const DOWNLOAD_FAILURE = 'DOWNLOAD_FAILURE'
export const DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS'

//not here
export const ItemTypes = { BOX: 'box' }